spring:
  application:
    name: roomBooking

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/room_booking
    username: root
    password: 87249293a

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: warn
    com.github.alefthallys: info

jwt:
    secret: u4pHe1gHY!dnM8nAq3VJ@vLyxRs#TpBZrW7cZf96m2@qX9WmFS
    expiration: 86400000
    issuer: roomBooking
    audience: roomBooking
    header: Authorization
    prefix: Bearer
    token:
        refresh:
        expiration: 604800000
        header: Refresh-Token
        prefix: Refresh