spring:
  application:
    name: roomBooking

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: ${JWT_ISSUER}
  audience: ${JWT_AUDIENCE}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}
  refreshSecret: ${JWT_REFRESHSECRET}
  refreshExpiration: ${JWT_REFRESHEXPIRATION}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env,loggers,httptrace,threaddump
  endpoint:
    health:
      show-details: always
    metrics:
      access: read_only
    httptrace:
      enabled: true
      buffer-size: 100

logging:
  level:
    root: warn
    com.github.alefthallys: info

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true