INSERT INTO rooms (name, description, capacity, available, location)
VALUES ('Room 1', 'A versatile room for meetings and presentations.', 10, TRUE, '1st Floor, North Wing'),
       ('Room 2', 'Comfortable space for small team collaborations.', 8, TRUE, '2nd Floor, South Wing'),
       ('Room 3', 'Large conference room with advanced AV equipment.', 30, TRUE, '3rd Floor, East Wing'),
       ('Room 4', 'Quiet study room, ideal for focused work.', 4, TRUE, 'Ground Floor, West Wing'),
       ('Room 5', 'Flexible training room with movable furniture.', 20, TRUE, '5th Floor, Central Area'),
       ('Room 6', 'Compact meeting room with whiteboard and screen.', 6, TRUE, '1st Floor, West Wing'),
       ('Room 7', 'Executive board room with video conferencing.', 15, TRUE, '4th Floor, North Wing'),
       ('Room 8', 'Creative workshop space with interactive displays.', 12, TRUE, '2nd Floor, East Wing'),
       ('Room 9', 'Spacious auditorium for large events and seminars.', 50, TRUE, 'Ground Floor, Auditorium Block'),
       ('Room 10', 'Small private office for one-on-one discussions.', 2, TRUE, '3rd Floor, South Wing'),
       ('Room 11', 'Multi-purpose room for various company activities.', 25, TRUE, '4th Floor, West Wing'),
       ('Room 12', 'Team huddle room with collaborative screen.', 7, TRUE, '1st Floor, Central Area'),
       ('Room 13', 'Bright and airy meeting room with natural light.', 10, TRUE, '2nd Floor, North Wing'),
       ('Room 14', 'Dedicated IT training lab with multiple workstations.', 18, TRUE, 'Ground Floor, Tech Hub'),
       ('Room 15', 'Informal lounge area for casual brainstorming.', 8, TRUE, '5th Floor, Lounge Area'),
       ('Room 16', 'Small conference room with teleconferencing facility.', 6, TRUE, '3rd Floor, East Wing'),
       ('Room 17', 'Boardroom with projection and sound system.', 14, TRUE, '1st Floor, South Wing'),
       ('Room 18', 'Creative space for design and innovation teams.', 11, TRUE, '4th Floor, Central Area'),
       ('Room 19', 'Presentation hall with seating for large groups.', 45, TRUE, 'Ground Floor, Event Hall'),
       ('Room 20', 'Cozy corner for quick catch-ups and breaks.', 3, TRUE, '2nd Floor, West Wing'),
       ('Room 21', 'A versatile room for meetings and presentations.', 10, TRUE, '1st Floor, North Wing'),
       ('Room 22', 'Comfortable space for small team collaborations.', 8, TRUE, '2nd Floor, South Wing'),
       ('Room 23', 'Large conference room with advanced AV equipment.', 30, TRUE, '3rd Floor, East Wing'),
       ('Room 24', 'Quiet study room, ideal for focused work.', 4, TRUE, 'Ground Floor, West Wing'),
       ('Room 25', 'Flexible training room with movable furniture.', 20, TRUE, '5th Floor, Central Area'),
       ('Room 26', 'Compact meeting room with whiteboard and screen.', 6, TRUE, '1st Floor, West Wing'),
       ('Room 27', 'Executive board room with video conferencing.', 15, TRUE, '4th Floor, North Wing'),
       ('Room 28', 'Creative workshop space with interactive displays.', 12, TRUE, '2nd Floor, East Wing'),
       ('Room 29', 'Spacious auditorium for large events and seminars.', 50, TRUE, 'Ground Floor, Auditorium Block'),
       ('Room 30', 'Small private office for one-on-one discussions.', 2, TRUE, '3rd Floor, South Wing'),
       ('Room 31', 'Multi-purpose room for various company activities.', 25, TRUE, '4th Floor, West Wing'),
       ('Room 32', 'Team huddle room with collaborative screen.', 7, TRUE, '1st Floor, Central Area'),
       ('Room 33', 'Bright and airy meeting room with natural light.', 10, TRUE, '2nd Floor, North Wing'),
       ('Room 34', 'Dedicated IT training lab with multiple workstations.', 18, TRUE, 'Ground Floor, Tech Hub'),
       ('Room 35', 'Informal lounge area for casual brainstorming.', 8, TRUE, '5th Floor, Lounge Area'),
       ('Room 36', 'Small conference room with teleconferencing facility.', 6, TRUE, '3rd Floor, East Wing'),
       ('Room 37', 'Boardroom with projection and sound system.', 14, TRUE, '1st Floor, South Wing'),
       ('Room 38', 'Creative space for design and innovation teams.', 11, TRUE, '4th Floor, Central Area'),
       ('Room 39', 'Presentation hall with seating for large groups.', 45, TRUE, 'Ground Floor, Event Hall'),
       ('Room 40', 'Cozy corner for quick catch-ups and breaks.', 3, TRUE, '2nd Floor, West Wing'),
       ('Room 41', 'A versatile room for meetings and presentations.', 10, TRUE, '1st Floor, North Wing'),
       ('Room 42', 'Comfortable space for small team collaborations.', 8, TRUE, '2nd Floor, South Wing'),
       ('Room 43', 'Large conference room with advanced AV equipment.', 30, TRUE, '3rd Floor, East Wing'),
       ('Room 44', 'Quiet study room, ideal for focused work.', 4, TRUE, 'Ground Floor, West Wing'),
       ('Room 45', 'Flexible training room with movable furniture.', 20, TRUE, '5th Floor, Central Area'),
       ('Room 46', 'Compact meeting room with whiteboard and screen.', 6, TRUE, '1st Floor, West Wing'),
       ('Room 47', 'Executive board room with video conferencing.', 15, TRUE, '4th Floor, North Wing'),
       ('Room 48', 'Creative workshop space with interactive displays.', 12, TRUE, '2nd Floor, East Wing'),
       ('Room 49', 'Spacious auditorium for large events and seminars.', 50, TRUE, 'Ground Floor, Auditorium Block'),
       ('Room 50', 'Small private office for one-on-one discussions.', 2, TRUE, '3rd Floor, South Wing'),
       ('Room 51', 'Multi-purpose room for various company activities.', 25, TRUE, '4th Floor, West Wing'),
       ('Room 52', 'Team huddle room with collaborative screen.', 7, TRUE, '1st Floor, Central Area'),
       ('Room 53', 'Bright and airy meeting room with natural light.', 10, TRUE, '2nd Floor, North Wing'),
       ('Room 54', 'Dedicated IT training lab with multiple workstations.', 18, TRUE, 'Ground Floor, Tech Hub'),
       ('Room 55', 'Informal lounge area for casual brainstorming.', 8, TRUE, '5th Floor, Lounge Area'),
       ('Room 56', 'Small conference room with teleconferencing facility.', 6, TRUE, '3rd Floor, East Wing'),
       ('Room 57', 'Boardroom with projection and sound system.', 14, TRUE, '1st Floor, South Wing'),
       ('Room 58', 'Creative space for design and innovation teams.', 11, TRUE, '4th Floor, Central Area'),
       ('Room 59', 'Presentation hall with seating for large groups.', 45, TRUE, 'Ground Floor, Event Hall'),
       ('Room 60', 'Cozy corner for quick catch-ups and breaks.', 3, TRUE, '2nd Floor, West Wing'),
       ('Room 61', 'A versatile room for meetings and presentations.', 10, TRUE, '1st Floor, North Wing'),
       ('Room 62', 'Comfortable space for small team collaborations.', 8, TRUE, '2nd Floor, South Wing'),
       ('Room 63', 'Large conference room with advanced AV equipment.', 30, TRUE, '3rd Floor, East Wing'),
       ('Room 64', 'Quiet study room, ideal for focused work.', 4, TRUE, 'Ground Floor, West Wing'),
       ('Room 65', 'Flexible training room with movable furniture.', 20, TRUE, '5th Floor, Central Area'),
       ('Room 66', 'Compact meeting room with whiteboard and screen.', 6, TRUE, '1st Floor, West Wing'),
       ('Room 67', 'Executive board room with video conferencing.', 15, TRUE, '4th Floor, North Wing'),
       ('Room 68', 'Creative workshop space with interactive displays.', 12, TRUE, '2nd Floor, East Wing'),
       ('Room 69', 'Spacious auditorium for large events and seminars.', 50, TRUE, 'Ground Floor, Auditorium Block'),
       ('Room 70', 'Small private office for one-on-one discussions.', 2, TRUE, '3rd Floor, South Wing'),
       ('Room 71', 'Multi-purpose room for various company activities.', 25, TRUE, '4th Floor, West Wing'),
       ('Room 72', 'Team huddle room with collaborative screen.', 7, TRUE, '1st Floor, Central Area'),
       ('Room 73', 'Bright and airy meeting room with natural light.', 10, TRUE, '2nd Floor, North Wing'),
       ('Room 74', 'Dedicated IT training lab with multiple workstations.', 18, TRUE, 'Ground Floor, Tech Hub'),
       ('Room 75', 'Informal lounge area for casual brainstorming.', 8, TRUE, '5th Floor, Lounge Area'),
       ('Room 76', 'Small conference room with teleconferencing facility.', 6, TRUE, '3rd Floor, East Wing'),
       ('Room 77', 'Boardroom with projection and sound system.', 14, TRUE, '1st Floor, South Wing'),
       ('Room 78', 'Creative space for design and innovation teams.', 11, TRUE, '4th Floor, Central Area'),
       ('Room 79', 'Presentation hall with seating for large groups.', 45, TRUE, 'Ground Floor, Event Hall'),
       ('Room 80', 'Cozy corner for quick catch-ups and breaks.', 3, TRUE, '2nd Floor, West Wing'),
       ('Room 81', 'A versatile room for meetings and presentations.', 10, TRUE, '1st Floor, North Wing'),
       ('Room 82', 'Comfortable space for small team collaborations.', 8, TRUE, '2nd Floor, South Wing'),
       ('Room 83', 'Large conference room with advanced AV equipment.', 30, TRUE, '3rd Floor, East Wing'),
       ('Room 84', 'Quiet study room, ideal for focused work.', 4, TRUE, 'Ground Floor, West Wing'),
       ('Room 85', 'Flexible training room with movable furniture.', 20, TRUE, '5th Floor, Central Area'),
       ('Room 86', 'Compact meeting room with whiteboard and screen.', 6, TRUE, '1st Floor, West Wing'),
       ('Room 87', 'Executive board room with video conferencing.', 15, TRUE, '4th Floor, North Wing'),
       ('Room 88', 'Creative workshop space with interactive displays.', 12, TRUE, '2nd Floor, East Wing'),
       ('Room 89', 'Spacious auditorium for large events and seminars.', 50, TRUE, 'Ground Floor, Auditorium Block'),
       ('Room 90', 'Small private office for one-on-one discussions.', 2, TRUE, '3rd Floor, South Wing'),
       ('Room 91', 'Multi-purpose room for various company activities.', 25, TRUE, '4th Floor, West Wing'),
       ('Room 92', 'Team huddle room with collaborative screen.', 7, TRUE, '1st Floor, Central Area'),
       ('Room 93', 'Bright and airy meeting room with natural light.', 10, TRUE, '2nd Floor, North Wing'),
       ('Room 94', 'Dedicated IT training lab with multiple workstations.', 18, TRUE, 'Ground Floor, Tech Hub'),
       ('Room 95', 'Informal lounge area for casual brainstorming.', 8, TRUE, '5th Floor, Lounge Area'),
       ('Room 96', 'Small conference room with teleconferencing facility.', 6, TRUE, '3rd Floor, East Wing'),
       ('Room 97', 'Boardroom with projection and sound system.', 14, TRUE, '1st Floor, South Wing'),
       ('Room 98', 'Creative space for design and innovation teams.', 11, TRUE, '4th Floor, Central Area'),
       ('Room 99', 'Presentation hall with seating for large groups.', 45, TRUE, 'Ground Floor, Event Hall'),
       ('Room 100', 'Cozy corner for quick catch-ups and breaks.', 3, TRUE, '2nd Floor, West Wing');